import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Headphones, Lightbulb, MessageCircle, Mic2, PenLine, Play, Sparkles, Target, Volume2, Waves, X } from 'lucide-react';
import { A1_LESSONS, A1ActivityKind } from '../data/a1LearningPath';
import { AudioButton } from './AudioButton';

interface Props { currentChapter?: number; onOpenVocabulary?: () => void; }

const iconFor = (kind: A1ActivityKind) => ({ dialogue: MessageCircle, story: BookOpen, audio: Headphones, vocabulary: Sparkles, grammar: Lightbulb, exercise: Target, speaking: Mic2, writing: PenLine, situation: Waves }[kind]);
const labelFor = (kind: A1ActivityKind) => ({ dialogue: 'Dialog', story: 'Mini-Story', audio: 'Hören', vocabulary: 'Wortschatz', grammar: 'Grammatik', exercise: 'Übung', speaking: 'Sprechen', writing: 'Schreiben', situation: 'Situation' }[kind]);

export const A1CourseExperience: React.FC<Props> = ({ currentChapter = 1, onOpenVocabulary }) => {
  const [selected, setSelected] = useState(Math.min(20, Math.max(1, currentChapter)));
  const [activeActivity, setActiveActivity] = useState(0);
  const [completed, setCompleted] = useState<number[]>(() => {
    try { return JSON.parse(localStorage.getItem('deutsch_a1_completed_lessons') || '[]'); } catch { return []; }
  });
  const current = A1_LESSONS[selected - 1];
  const activity = current.subLessons[activeActivity];
  const ActivityIcon = iconFor(activity.kind);
  const progress = Math.round((completed.length / A1_LESSONS.length) * 100);
  useEffect(() => { localStorage.setItem('deutsch_a1_completed_lessons', JSON.stringify(completed)); }, [completed]);
  useEffect(() => { setActiveActivity(0); }, [selected]);
  const done = completed.includes(current.number);
  const next = () => { if (selected < 20) setSelected(selected + 1); };
  const previous = () => { if (selected > 1) setSelected(selected - 1); };
  const toggleDone = () => setCompleted((items) => done ? items.filter((item) => item !== current.number) : [...items, current.number].sort((a, b) => a - b));

  return <div className="space-y-6 pb-8">
    <section className="relative overflow-hidden rounded-[2rem] bg-slate-950 text-white shadow-xl">
      <div className="absolute -right-16 -top-24 h-72 w-72 rounded-full bg-indigo-500/25 blur-3xl" />
      <div className="absolute -bottom-24 left-1/3 h-56 w-56 rounded-full bg-cyan-400/10 blur-3xl" />
      <div className="relative grid gap-8 p-6 sm:p-8 lg:grid-cols-[1.25fr_.75fr] lg:p-10">
        <div>
          <div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-indigo-300"><Sparkles className="h-4 w-4" /> A1 · Grundstufe</div>
          <h1 className="max-w-xl font-display text-4xl font-black tracking-tight sm:text-5xl">Deutsch lernen, Schritt für Schritt.</h1>
          <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">Ein klarer Lernpfad für echte Situationen: hören, sprechen, entdecken und direkt anwenden — mit 20 Lektionen von „Hallo“ bis zur A1-Prüfung.</p>
          <div className="mt-7 flex flex-wrap gap-3"><button onClick={() => setActiveActivity(0)} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-900 shadow-lg transition hover:bg-indigo-50"><Play className="h-4 w-4 fill-current" /> Lektion fortsetzen</button><button onClick={onOpenVocabulary} className="inline-flex items-center gap-2 rounded-xl border border-white/20 px-4 py-2.5 text-sm font-bold text-white transition hover:bg-white/10"><BookOpen className="h-4 w-4" /> Wortschatz öffnen</button></div>
        </div>
        <div className="flex items-end lg:justify-end"><div className="w-full max-w-xs rounded-2xl border border-white/10 bg-white/[.08] p-5 backdrop-blur"><div className="flex items-center justify-between text-sm"><span className="font-semibold text-slate-300">Dein Fortschritt</span><span className="font-black text-white">{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-indigo-400 transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-4 flex items-end justify-between"><div><div className="text-3xl font-black">{completed.length}<span className="text-base text-slate-400"> / 20</span></div><div className="text-xs text-slate-400">Lektionen abgeschlossen</div></div><Target className="h-8 w-8 text-cyan-300" /></div></div></div>
      </div>
    </section>

    <div className="grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]">
      <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-4 shadow-sm lg:sticky lg:top-6"><div className="mb-4 flex items-center justify-between px-2"><div><h2 className="font-display text-lg font-black">Dein Lernpfad</h2><p className="text-xs text-slate-500">20 Lektionen · A1</p></div><span className="rounded-lg bg-indigo-50 px-2 py-1 text-xs font-bold text-indigo-700">{completed.length}/20</span></div><div className="space-y-1">{A1_LESSONS.map((item) => { const isSelected = item.number === selected; const isDone = completed.includes(item.number); return <button key={item.number} onClick={() => setSelected(item.number)} className={`group flex w-full items-center gap-3 rounded-2xl p-2.5 text-left transition ${isSelected ? 'bg-slate-900 text-white shadow-md' : 'hover:bg-slate-50'}`}><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-xl text-xs font-black ${isDone ? 'bg-emerald-500 text-white' : isSelected ? 'bg-white/15 text-white' : 'bg-slate-100 text-slate-600'}`}>{isDone ? <Check className="h-4 w-4" /> : item.number}</span><span className="min-w-0"><span className={`block truncate text-xs font-bold ${isSelected ? 'text-white' : 'text-slate-800'}`}>{item.title}</span><span className={`block truncate text-[10px] ${isSelected ? 'text-slate-300' : 'text-slate-500'}`}>{item.unit}</span></span><ChevronRight className={`ml-auto h-4 w-4 shrink-0 ${isSelected ? 'text-white' : 'text-slate-300 group-hover:text-slate-600'}`} /></button>; })}</div></aside>

      <main className="min-w-0 space-y-6">
        <section className={`overflow-hidden rounded-3xl bg-gradient-to-br ${current.color} p-6 text-white shadow-lg sm:p-8`}><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="mb-3 text-xs font-bold uppercase tracking-[.18em] text-white/70">Lektion {String(current.number).padStart(2, '0')} · {current.unit}</div><h2 className="font-display text-3xl font-black tracking-tight sm:text-4xl">{current.title}</h2><p className="mt-2 text-sm text-white/80">{current.subtitle}</p></div><button onClick={toggleDone} className={`inline-flex shrink-0 items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition ${done ? 'bg-white text-emerald-700' : 'bg-white/15 text-white hover:bg-white/25'}`}>{done ? <Check className="h-4 w-4" /> : <Target className="h-4 w-4" />}{done ? 'Abgeschlossen' : 'Als gelernt markieren'}</button></div><div className="mt-8 grid gap-2 sm:grid-cols-3">{current.goals.map((goal) => <div key={goal} className="rounded-xl border border-white/15 bg-white/10 p-3 text-xs font-semibold leading-5">{goal}</div>)}</div></section>

        <section className="grid gap-6 xl:grid-cols-[.95fr_1.05fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-display text-xl font-black">Lernstationen</h3><p className="mt-1 text-xs text-slate-500">Wähle deinen nächsten Schritt.</p></div><span className="text-xs font-bold text-slate-400">{current.subLessons.length} Stationen</span></div><div className="space-y-2">{current.subLessons.map((item, index) => { const Icon = iconFor(item.kind); const active = activeActivity === index; return <button key={item.id} onClick={() => setActiveActivity(index)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition ${active ? 'border-indigo-300 bg-indigo-50 shadow-sm' : 'border-slate-100 hover:border-slate-200 hover:bg-slate-50'}`}><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${active ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-500'}`}><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-sm font-bold text-slate-900">{item.title}</span><span className="hidden rounded-md bg-slate-100 px-1.5 py-0.5 text-[10px] font-bold text-slate-500 sm:inline">{labelFor(item.kind)}</span></span><span className="mt-1 block text-xs text-slate-500">{item.description}</span></span><span className="shrink-0 text-[10px] font-bold text-slate-400">{item.duration}</span></button>; })}</div></div>

        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-600"><ActivityIcon className="h-4 w-4" /> {labelFor(activity.kind)}</div><h3 className="font-display text-2xl font-black text-slate-900">{activity.title}</h3><p className="mt-1 text-sm text-slate-500">{activity.description}</p></div><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold text-slate-500">{activity.duration}</span></div><ActivityPanel kind={activity.kind} lesson={current.number} onOpenVocabulary={onOpenVocabulary} /></div></section>

        <div className="flex flex-col justify-between gap-3 sm:flex-row"><button disabled={selected === 1} onClick={previous} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 shadow-sm transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-40"><ArrowLeft className="h-4 w-4" /> Vorherige Lektion</button><button disabled={selected === 20} onClick={next} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-40">Nächste Lektion <ArrowRight className="h-4 w-4" /></button></div>
      </main>
    </div>
  </div>;
};

const ActivityPanel: React.FC<{ kind: A1ActivityKind; lesson: number; onOpenVocabulary?: () => void }> = ({ kind, lesson, onOpenVocabulary }) => {
  if (kind === 'audio') return <div className="rounded-2xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-500"><Volume2 className="h-6 w-6" /></div><div><p className="font-bold">Höre den Beispielsatz</p><p className="text-xs text-slate-400">Mehrmals hören und nachsprechen</p></div><AudioButton text="Guten Tag, ich lerne Deutsch." size="lg" label="Anhören" /></div><div className="mt-6 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/5 rounded-full bg-indigo-400" /></div></div>;
  if (kind === 'vocabulary') return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-indigo-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Wortschatz entdecken</p><p className="mt-2 text-lg font-black text-slate-900">der Name</p><p className="text-sm text-slate-600">Wie heißt du? — Ich heiße Lina.</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Merksatz</p><p className="mt-2 text-sm font-semibold leading-6 text-slate-800">Sprich jedes neue Wort laut und benutze es sofort in einem Satz.</p></div></div><button onClick={onOpenVocabulary} className="text-sm font-bold text-indigo-700 hover:underline">Mehr Wörter im Wortschatz ansehen →</button></div>;
  if (kind === 'grammar') return <div className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-5"><div className="grid gap-3 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Muster</p><p className="mt-2 font-mono text-lg font-black text-slate-900">Ich bin · du bist · er ist</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Beispiel</p><p className="mt-2 text-sm font-semibold text-slate-800">Ich bin Othmane. Du bist neu hier.</p></div></div></div>;
  if (kind === 'exercise') return <div className="space-y-4"><p className="font-bold text-slate-900">Welche Antwort passt?</p><div className="grid gap-2 sm:grid-cols-2"><button className="rounded-xl border border-slate-200 p-3 text-left text-sm font-semibold transition hover:border-indigo-400 hover:bg-indigo-50">Ich heiße Sara.</button><button className="rounded-xl border border-slate-200 p-3 text-left text-sm font-semibold transition hover:border-indigo-400 hover:bg-indigo-50">Ich bin aus Berlin.</button></div><p className="text-xs text-slate-500">Klicke auf eine Antwort und sprich sie laut nach.</p></div>;
  if (kind === 'speaking' || kind === 'writing') return <div className="space-y-4"><div className="rounded-2xl bg-amber-50 p-5"><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Deine Aufgabe</p><p className="mt-2 font-bold leading-6 text-slate-900">{kind === 'speaking' ? 'Stell dich in drei Sätzen vor. Sprich frei und deutlich.' : 'Schreibe drei Sätze über deinen Alltag.'}</p></div><textarea rows={3} placeholder={kind === 'speaking' ? 'Notizen für deine Antwort …' : 'Deine Antwort auf Deutsch …'} className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-indigo-500 focus:bg-white" /><button className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white"><Check className="h-4 w-4" /> Aufgabe speichern</button></div>;
  return <div className="space-y-4"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs font-bold uppercase tracking-wider text-indigo-600">Echte Situation</p><p className="mt-2 text-lg font-black text-slate-900">„Guten Tag! Wie geht es Ihnen?“</p><p className="mt-2 text-sm leading-6 text-slate-600">Lies den kurzen Dialog. Achte darauf, wie die Personen höflich reagieren und das Gespräch weiterführen.</p></div><div className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><span className="rounded-lg bg-indigo-100 px-2 py-1 text-xs font-bold text-indigo-700">A{lesson}</span><p className="text-sm font-semibold text-slate-800">Jetzt bist du dran: Antworte mit einem vollständigen Satz.</p><AudioButton text="Guten Tag! Wie geht es Ihnen?" /></div></div>;
};
